services:
  jenkins:
    image: jenkins-with-docker
    container_name: jenkins
    user: root
    ports:
      - "8082:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock  # <--- este SÃ es necesario
volumes:
  jenkins_home:
